/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package programa;

import java.awt.Color;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Iván Estévez Sabucedo
 */
public class Reserva extends javax.swing.JDialog {

    private final String TIPO_EVENTO_BANQUETE = "Banquete";
    private final String TIPO_EVENTO_JORNADA = "Jornada";
    private final String TIPO_EVENTO_CONGRESO = "Congreso";

    private final String TIPO_RESTAURANTE_BUFE = "Bufé";
    private final String TIPO_RESTAURANTE_CARTA = "Carta";
    private final String TIPO_RESTAURANTE_CHEF = "Cita con el chef";
    private final String TIPO_RESTAURANTE_NA = "No precisa";

    private final String SI = "Sí";
    private final String NO = "No";

    /**
     * Creates new form NewJDialog
     */
    public Reserva(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        configFecha();
        configComboTipoEvento();
        configComboTipoRestaurante();
        configSpinnerAlojamiento();
        configSpinnerAsistentes();
        configSpinnerNumHabitaciones();
        panelCongreso.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoAlojamiento = new javax.swing.ButtonGroup();
        etiquetaPrincipal = new javax.swing.JLabel();
        separadorTituloContacto = new javax.swing.JSeparator();
        panelContacto = new javax.swing.JPanel();
        etiquetaNombre = new javax.swing.JLabel();
        etiquetaTelefono = new javax.swing.JLabel();
        textoNombre = new javax.swing.JTextField();
        textoTelefono = new javax.swing.JTextField();
        separadorContactoReserva = new javax.swing.JSeparator();
        panelReserva = new javax.swing.JPanel();
        etiquetaFecha = new javax.swing.JLabel();
        spinnerFecha = new javax.swing.JSpinner();
        etiquetaAsistentes = new javax.swing.JLabel();
        spinnerAsistentes = new javax.swing.JSpinner();
        etiquetaTipo = new javax.swing.JLabel();
        comboBoxTipoEvento = new javax.swing.JComboBox<>();
        etiquetaRestaurante = new javax.swing.JLabel();
        comboBoxRestaurante = new javax.swing.JComboBox<>();
        panelCongreso = new javax.swing.JLayeredPane();
        etiquetaDias = new javax.swing.JLabel();
        spinnerAlojamiento = new javax.swing.JSpinner();
        etiquetaAlojamiento = new javax.swing.JLabel();
        botonSi = new javax.swing.JRadioButton();
        botonNo = new javax.swing.JRadioButton();
        etiquetaNumHabitaciones = new javax.swing.JLabel();
        spinnerNumHabitaciones = new javax.swing.JSpinner();
        botonConfirmar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Salón Habana - Central de reservas");
        setBackground(new java.awt.Color(255, 204, 153));

        etiquetaPrincipal.setBackground(new java.awt.Color(255, 204, 153));
        etiquetaPrincipal.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        etiquetaPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaPrincipal.setText("Salón Habana");
        etiquetaPrincipal.setToolTipText("Nombre del establecimiento");

        separadorTituloContacto.setToolTipText("Separador de secciones");

        panelContacto.setBackground(new java.awt.Color(255, 255, 255));
        panelContacto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de contacto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 14))); // NOI18N
        panelContacto.setToolTipText("Datos de contacto");
        panelContacto.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N

        etiquetaNombre.setFont(new java.awt.Font("SansSerif", 3, 11)); // NOI18N
        etiquetaNombre.setText("Nombre y apellidos");
        etiquetaNombre.setToolTipText("Nombre y apellidos");

        etiquetaTelefono.setFont(new java.awt.Font("SansSerif", 3, 11)); // NOI18N
        etiquetaTelefono.setText("Teléfono");
        etiquetaTelefono.setToolTipText("Teléfono de contacto");

        textoNombre.setToolTipText("Nombre y apellidos");
        textoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoNombreActionPerformed(evt);
            }
        });

        textoTelefono.setToolTipText("Teléfono de contacto");
        textoTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoTelefonoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelContactoLayout = new javax.swing.GroupLayout(panelContacto);
        panelContacto.setLayout(panelContactoLayout);
        panelContactoLayout.setHorizontalGroup(
            panelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContactoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiquetaNombre)
                    .addComponent(etiquetaTelefono))
                .addGap(18, 18, 18)
                .addGroup(panelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelContactoLayout.createSequentialGroup()
                        .addComponent(textoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(textoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panelContactoLayout.setVerticalGroup(
            panelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContactoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaNombre)
                    .addComponent(textoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaTelefono)
                    .addComponent(textoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        separadorContactoReserva.setToolTipText("Separador de secciones");

        panelReserva.setBackground(new java.awt.Color(255, 255, 255));
        panelReserva.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de la reserva", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 14))); // NOI18N
        panelReserva.setToolTipText("Datos de la reserva");

        etiquetaFecha.setFont(new java.awt.Font("SansSerif", 3, 11)); // NOI18N
        etiquetaFecha.setText("Fecha deseada");
        etiquetaFecha.setToolTipText("Fecha del evento");

        spinnerFecha.setToolTipText("Selecciona la fecha");

        etiquetaAsistentes.setFont(new java.awt.Font("SansSerif", 3, 11)); // NOI18N
        etiquetaAsistentes.setText("Asistentes");
        etiquetaAsistentes.setToolTipText("Asistentes al evento");

        spinnerAsistentes.setToolTipText("Selecciona el número de asistentes");

        etiquetaTipo.setFont(new java.awt.Font("SansSerif", 3, 11)); // NOI18N
        etiquetaTipo.setText("Tipo de evento");
        etiquetaTipo.setToolTipText("Tipo de evento a reservar");

        comboBoxTipoEvento.setMaximumRowCount(3);
        comboBoxTipoEvento.setToolTipText("Selecciona el tipo de evento");
        comboBoxTipoEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxTipoEventoActionPerformed(evt);
            }
        });

        etiquetaRestaurante.setFont(new java.awt.Font("SansSerif", 3, 11)); // NOI18N
        etiquetaRestaurante.setText("Restaurante");
        etiquetaRestaurante.setToolTipText("Tipo de restaurante");

        comboBoxRestaurante.setMaximumRowCount(4);
        comboBoxRestaurante.setToolTipText("Selecciona el tipo de restaurante");
        comboBoxRestaurante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxRestauranteActionPerformed(evt);
            }
        });

        panelCongreso.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Datos del congreso", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 12))); // NOI18N
        panelCongreso.setToolTipText("Panel para los datos de Congreso");

        etiquetaDias.setFont(new java.awt.Font("SansSerif", 3, 11)); // NOI18N
        etiquetaDias.setText("Días");
        etiquetaDias.setToolTipText("Días de alojamiento");

        spinnerAlojamiento.setToolTipText("Selecciona los días de alojamiento");

        etiquetaAlojamiento.setFont(new java.awt.Font("SansSerif", 3, 11)); // NOI18N
        etiquetaAlojamiento.setText("Alojamiento");
        etiquetaAlojamiento.setToolTipText("Selecciona que sí precisas alojamientoconfigComboTipoEvento");

        grupoAlojamiento.add(botonSi);
        botonSi.setText("Sí");
        botonSi.setToolTipText("Selecciona que sí precisas alojamiento");
        botonSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSiActionPerformed(evt);
            }
        });

        grupoAlojamiento.add(botonNo);
        botonNo.setSelected(true);
        botonNo.setText("No");
        botonNo.setToolTipText("Selecciona que no precisas alojamiento");
        botonNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNoActionPerformed(evt);
            }
        });

        etiquetaNumHabitaciones.setFont(new java.awt.Font("SansSerif", 3, 11)); // NOI18N
        etiquetaNumHabitaciones.setText("Habitaciones");
        etiquetaNumHabitaciones.setToolTipText("Número de habitaciones necesarias");

        spinnerNumHabitaciones.setToolTipText("Selecciona el número de habitaciones");
        spinnerNumHabitaciones.setEnabled(false);

        panelCongreso.setLayer(etiquetaDias, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelCongreso.setLayer(spinnerAlojamiento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelCongreso.setLayer(etiquetaAlojamiento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelCongreso.setLayer(botonSi, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelCongreso.setLayer(botonNo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelCongreso.setLayer(etiquetaNumHabitaciones, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelCongreso.setLayer(spinnerNumHabitaciones, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panelCongresoLayout = new javax.swing.GroupLayout(panelCongreso);
        panelCongreso.setLayout(panelCongresoLayout);
        panelCongresoLayout.setHorizontalGroup(
            panelCongresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCongresoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelCongresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCongresoLayout.createSequentialGroup()
                        .addComponent(botonSi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonNo))
                    .addComponent(etiquetaAlojamiento)
                    .addComponent(etiquetaNumHabitaciones)
                    .addGroup(panelCongresoLayout.createSequentialGroup()
                        .addComponent(etiquetaDias, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spinnerAlojamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(spinnerNumHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );
        panelCongresoLayout.setVerticalGroup(
            panelCongresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCongresoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCongresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaDias)
                    .addComponent(spinnerAlojamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(etiquetaAlojamiento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCongresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonSi)
                    .addComponent(botonNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(etiquetaNumHabitaciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spinnerNumHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelReservaLayout = new javax.swing.GroupLayout(panelReserva);
        panelReserva.setLayout(panelReservaLayout);
        panelReservaLayout.setHorizontalGroup(
            panelReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReservaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiquetaFecha)
                    .addComponent(etiquetaAsistentes)
                    .addComponent(etiquetaTipo)
                    .addComponent(etiquetaRestaurante))
                .addGap(34, 34, 34)
                .addGroup(panelReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(spinnerFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(comboBoxTipoEvento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboBoxRestaurante, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spinnerAsistentes))
                .addGap(18, 18, 18)
                .addComponent(panelCongreso, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelReservaLayout.setVerticalGroup(
            panelReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelReservaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaFecha)
                    .addComponent(spinnerFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaAsistentes)
                    .addComponent(spinnerAsistentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaTipo)
                    .addComponent(comboBoxTipoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaRestaurante)
                    .addComponent(comboBoxRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77))
            .addGroup(panelReservaLayout.createSequentialGroup()
                .addComponent(panelCongreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        botonConfirmar.setBackground(new java.awt.Color(204, 255, 204));
        botonConfirmar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botonConfirmar.setText("Confirmar reserva");
        botonConfirmar.setToolTipText("Confirma la reserva");
        botonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConfirmarActionPerformed(evt);
            }
        });

        botonCancelar.setBackground(new java.awt.Color(255, 204, 204));
        botonCancelar.setText("Cancelar");
        botonCancelar.setToolTipText("Cancela la reserva");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(separadorTituloContacto)
            .addComponent(separadorContactoReserva)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelContacto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiquetaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(botonConfirmar)
                        .addGap(24, 24, 24)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(etiquetaPrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separadorTituloContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separadorContactoReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCancelar)
                    .addComponent(botonConfirmar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoNombreActionPerformed

    private void textoTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoTelefonoActionPerformed

    private void comboBoxTipoEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxTipoEventoActionPerformed
        JComboBox cb = (JComboBox) evt.getSource();
        String opcion = (String) cb.getSelectedItem();
        if (opcion.equals(TIPO_EVENTO_CONGRESO)) {
            panelCongreso.setVisible(true);
        } else {
            panelCongreso.setVisible(false);
        }

    }//GEN-LAST:event_comboBoxTipoEventoActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void comboBoxRestauranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxRestauranteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxRestauranteActionPerformed

    private void botonSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSiActionPerformed
        // TODO add your handling code here:
        String action = evt.getActionCommand();
        if (action.equals(SI)) {
            spinnerNumHabitaciones.setEnabled(true);
        }
    }//GEN-LAST:event_botonSiActionPerformed

    private void botonNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNoActionPerformed
        String action = evt.getActionCommand();
        if (action.equals(NO)) {
            spinnerNumHabitaciones.setEnabled(false);
        }
    }//GEN-LAST:event_botonNoActionPerformed

    private void botonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConfirmarActionPerformed
        if (textoNombre.getText().equals("")
                || textoTelefono.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Hay campos sin cubrir", "Error", 0);
        } else {
            JOptionPane.showMessageDialog(null, "Reserva realizada", "Éxito", 1);
            dispose();
        }
    }//GEN-LAST:event_botonConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Reserva dialog = new Reserva(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private void configFecha() {
        // Variable de objeto Calendar
        Calendar calendario = Calendar.getInstance();
        // Fecha de inicio será la actual del sistema
        Date fechaInicio = calendario.getTime();
        // Creamos un modelo con lo creado antes        
        SpinnerModel calModel = new SpinnerDateModel(fechaInicio, null, null, Calendar.YEAR);
        // Indicamos el modelo y el formato de fecha
        spinnerFecha.setModel(calModel);
        spinnerFecha.setEditor(new JSpinner.DateEditor(spinnerFecha, "dd/MM/yyyy"));

    }

    private void configComboTipoEvento() {
        String[] opciones = {TIPO_EVENTO_BANQUETE, TIPO_EVENTO_JORNADA, TIPO_EVENTO_CONGRESO};
        JComboBox<String> cb = new JComboBox(opciones);

        for (String s : opciones) {
            comboBoxTipoEvento.addItem(s);
        }
    }

    private void configComboTipoRestaurante() {
        String[] opciones = {TIPO_RESTAURANTE_BUFE, TIPO_RESTAURANTE_CARTA, TIPO_RESTAURANTE_CHEF, TIPO_RESTAURANTE_NA};
        JComboBox<String> cb = new JComboBox(opciones);

        for (String s : opciones) {
            comboBoxRestaurante.addItem(s);
        }
    }

    private void configSpinnerAlojamiento() {
        SpinnerModel sm = new SpinnerNumberModel(1, 1, null, 1); //default value,lower bound,upper bound,increment by
        spinnerAlojamiento.setModel(sm);
    }

    private void configSpinnerAsistentes() {
        SpinnerModel sm = new SpinnerNumberModel(1, 1, null, 1); //default value,lower bound,upper bound,increment by

        spinnerAsistentes.setModel(sm);
    }

    private void configSpinnerNumHabitaciones() {
        SpinnerModel sm = new SpinnerNumberModel(1, 0, null, 1); //default value,lower bound,upper bound,increment by
        spinnerNumHabitaciones.setModel(sm);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonConfirmar;
    private javax.swing.JRadioButton botonNo;
    private javax.swing.JRadioButton botonSi;
    private javax.swing.JComboBox<String> comboBoxRestaurante;
    private javax.swing.JComboBox<String> comboBoxTipoEvento;
    private javax.swing.JLabel etiquetaAlojamiento;
    private javax.swing.JLabel etiquetaAsistentes;
    private javax.swing.JLabel etiquetaDias;
    private javax.swing.JLabel etiquetaFecha;
    private javax.swing.JLabel etiquetaNombre;
    private javax.swing.JLabel etiquetaNumHabitaciones;
    private javax.swing.JLabel etiquetaPrincipal;
    private javax.swing.JLabel etiquetaRestaurante;
    private javax.swing.JLabel etiquetaTelefono;
    private javax.swing.JLabel etiquetaTipo;
    private javax.swing.ButtonGroup grupoAlojamiento;
    private javax.swing.JLayeredPane panelCongreso;
    private javax.swing.JPanel panelContacto;
    private javax.swing.JPanel panelReserva;
    private javax.swing.JSeparator separadorContactoReserva;
    private javax.swing.JSeparator separadorTituloContacto;
    private javax.swing.JSpinner spinnerAlojamiento;
    private javax.swing.JSpinner spinnerAsistentes;
    private javax.swing.JSpinner spinnerFecha;
    private javax.swing.JSpinner spinnerNumHabitaciones;
    private javax.swing.JTextField textoNombre;
    private javax.swing.JTextField textoTelefono;
    // End of variables declaration//GEN-END:variables
}
