package Vista;

import Contador.*; //J
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author Ignacio Brea Lodeiro
 */
public class Dreams extends JFrame implements ContadorEventListener {

    Contador miContador = new Contador();
    private boolean espera = true;
    private int numImagen;
    private List<ImageIcon> imagenes; //J

    /**
     * Creates new form Dreams
     */
    public Dreams() {
        initComponents();
        this.setLocationRelativeTo(null);
        setContador(miContador);

        miContador.addPropertyChangeListener(new PropertyChangeListener() {
            @Override
            public void propertyChange(PropertyChangeEvent evt) {
                if (evt.getPropertyName().equals("text")) {
                    lblContador.setText((String) evt.getNewValue());
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRomantica = new javax.swing.JButton();
        btnTerror = new javax.swing.JButton();
        btnInfantil = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        jPanelPrincipal = new javax.swing.JPanel();
        jPanelSecundario = new javax.swing.JPanel();
        lblHistoria01 = new javax.swing.JLabel();
        lblHistoria02 = new javax.swing.JLabel();
        lblHistoria03 = new javax.swing.JLabel();
        btnReiniciar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lblContador = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1200, 1024));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRomantica.setText("ROMÁNTICA");
        btnRomantica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRomanticaActionPerformed(evt);
            }
        });
        getContentPane().add(btnRomantica, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, -1, -1));

        btnTerror.setText("TERROR");
        btnTerror.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerrorActionPerformed(evt);
            }
        });
        getContentPane().add(btnTerror, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 30, -1, -1));

        btnInfantil.setText("INFANTIL");
        btnInfantil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfantilActionPerformed(evt);
            }
        });
        getContentPane().add(btnInfantil, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        lblTitulo.setFont(new java.awt.Font("Segoe Script", 3, 14)); // NOI18N
        lblTitulo.setText("SUEÑOS DORADOS PRESENTA");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 6, -1, -1));

        jPanelSecundario.setPreferredSize(new java.awt.Dimension(250, 550));

        javax.swing.GroupLayout jPanelSecundarioLayout = new javax.swing.GroupLayout(jPanelSecundario);
        jPanelSecundario.setLayout(jPanelSecundarioLayout);
        jPanelSecundarioLayout.setHorizontalGroup(
            jPanelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSecundarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblHistoria01, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblHistoria02, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblHistoria03, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        jPanelSecundarioLayout.setVerticalGroup(
            jPanelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSecundarioLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(jPanelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHistoria01, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHistoria03, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHistoria02, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnReiniciar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReiniciar.setText("Reiniciar");
        btnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        lblContador.setBackground(new java.awt.Color(204, 204, 204));
        lblContador.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblContador.setForeground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanelSecundario, javax.swing.GroupLayout.PREFERRED_SIZE, 1050, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(btnReiniciar)
                .addGap(278, 278, 278)
                .addComponent(lblContador, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(174, 174, 174))
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanelSecundario, javax.swing.GroupLayout.PREFERRED_SIZE, 781, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReiniciar)
                    .addComponent(btnSalir)
                    .addComponent(lblContador, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 84, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTerrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerrorActionPerformed
        aspectoEscena("Segoe Print", Color.RED);
        List<ImageIcon> lista = new ArrayList<>();
        lista.add(new ImageIcon(getClass().getResource("/Imagenes/terror1.jpg")));
        lista.add(new ImageIcon(getClass().getResource("/Imagenes/terror2.jpg")));
        lista.add(new ImageIcon(getClass().getResource("/Imagenes/terror3.jpg")));
        this.setBackground(Color.DARK_GRAY);
        this.imagenes = lista;
        this.numImagen = 0;
        this.limpiarEscena();
        this.cargarEscena(5);
    }//GEN-LAST:event_btnTerrorActionPerformed

    private void btnInfantilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfantilActionPerformed
        aspectoEscena("Ink Free", Color.GREEN);
        List<ImageIcon> lista = new ArrayList<>();
        lista.add(new ImageIcon(getClass().getResource("/Imagenes/infantil1.jpg")));
        lista.add(new ImageIcon(getClass().getResource("/Imagenes/infantil2.jpg")));
        lista.add(new ImageIcon(getClass().getResource("/Imagenes/infantil3.jpg")));
        this.setBackground(Color.yellow);
        this.imagenes = lista;
        this.numImagen = 0;
        this.limpiarEscena();
        this.cargarEscena(5);
    }//GEN-LAST:event_btnInfantilActionPerformed

    private void btnRomanticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRomanticaActionPerformed
        aspectoEscena("Gabriola", Color.PINK);
        List<ImageIcon> lista = new ArrayList<>();
        lista.add(new ImageIcon(getClass().getResource("/Imagenes/romantica1.jpg")));
        lista.add(new ImageIcon(getClass().getResource("/Imagenes/romantica2.jpg")));
        lista.add(new ImageIcon(getClass().getResource("/Imagenes/romantica3.jpg")));
        this.setBackground(Color.PINK);
        this.imagenes = lista;
        this.numImagen = 0;
        this.limpiarEscena();
        this.cargarEscena(5);
    }//GEN-LAST:event_btnRomanticaActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
        this.limpiarEscena();
        this.numImagen = 0;
        if (imagenes != null) {
        cargarEscena(5);
        }
    }//GEN-LAST:event_btnReiniciarActionPerformed

    public void setContador(Contador miContador) {
        this.miContador = miContador;
        this.miContador.addContadorEventListener(this);
    }

    public void cargarEscena(int tiempoEspera) {
        if (this.numImagen <= 2) {
            miContador.iniciarCuenta(tiempoEspera);
        } else {
           miContador.pararCuenta();
        }
    }

    @Override
    public void inicioCuenta(ContadorEventObject e) {
        switch (this.numImagen) {
            case 0 -> lblHistoria01.setIcon(imagenes.get(this.numImagen));
            case 1 -> lblHistoria02.setIcon(imagenes.get(this.numImagen));
            case 2 -> lblHistoria03.setIcon(imagenes.get(this.numImagen));
        }
    }

    @Override
    public void finCuenta(ContadorEventObject e) {
        this.numImagen++;
        miContador.pararCuenta();
        if (this.numImagen <= 2) {
            System.out.println("Banderitaaaaaaaaaaaaaaaaa");
            cargarEscena(5);
        } else {
            System.out.println("La imagen es " + numImagen);
            lblContador.setText("");
        }
    }

    private void limpiarEscena() {
        miContador.pararCuenta();

        lblHistoria01.setIcon(null);
        lblHistoria02.setIcon(null);
        lblHistoria03.setIcon(null);
    }
    
    private void aspectoEscena(String fuente, Color color) {
        btnInfantil.setFont(new Font(fuente, Font.BOLD, 16));
        btnTerror.setFont(new Font(fuente, Font.BOLD, 16));
        btnRomantica.setFont(new Font(fuente, Font.BOLD, 16));
        btnReiniciar.setFont(new Font(fuente, Font.BOLD, 16));
        btnSalir.setFont(new Font(fuente, Font.BOLD, 16));
        btnInfantil.setBackground(color);
        btnInfantil.setBackground(color);
        btnTerror.setBackground(color);
        btnRomantica.setBackground(color);
        btnReiniciar.setBackground(color);
        btnSalir.setBackground(color);
        jPanelPrincipal.setBackground(color);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dreams.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dreams.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dreams.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dreams.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dreams().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInfantil;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JButton btnRomantica;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnTerror;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JPanel jPanelSecundario;
    private javax.swing.JLabel lblContador;
    private javax.swing.JLabel lblHistoria01;
    private javax.swing.JLabel lblHistoria02;
    private javax.swing.JLabel lblHistoria03;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
