/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import components.reproductor.Imagen;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;

/**
 *
 * @author Iván Estévez Sabucedo
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public MainFrame() {
        initComponents();
        panelReproductor.setContador(contador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelSelector = new javax.swing.JPanel();
        botonInfanil = new javax.swing.JButton();
        botonRomantica = new javax.swing.JButton();
        botonTerror = new javax.swing.JButton();
        panelReproductor = new components.reproductor.ReproductorBean();
        panelAcciones = new javax.swing.JPanel();
        botonReiniciar = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        contador = new components.contador.ContadorBean();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CuentaCuentos");
        setResizable(false);

        panelPrincipal.setBackground(new java.awt.Color(0, 51, 255));

        panelSelector.setBackground(new java.awt.Color(255, 102, 102));

        botonInfanil.setText("INFANTIL");
        botonInfanil.setMaximumSize(new java.awt.Dimension(100, 25));
        botonInfanil.setMinimumSize(new java.awt.Dimension(100, 25));
        botonInfanil.setPreferredSize(new java.awt.Dimension(100, 25));
        botonInfanil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInfanilActionPerformed(evt);
            }
        });

        botonRomantica.setText("ROMÁNTICA");
        botonRomantica.setMaximumSize(new java.awt.Dimension(100, 25));
        botonRomantica.setMinimumSize(new java.awt.Dimension(100, 25));
        botonRomantica.setPreferredSize(new java.awt.Dimension(100, 25));
        botonRomantica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRomanticaActionPerformed(evt);
            }
        });

        botonTerror.setText("TERROR");
        botonTerror.setMaximumSize(new java.awt.Dimension(100, 25));
        botonTerror.setMinimumSize(new java.awt.Dimension(100, 25));
        botonTerror.setPreferredSize(new java.awt.Dimension(100, 25));
        botonTerror.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTerrorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSelectorLayout = new javax.swing.GroupLayout(panelSelector);
        panelSelector.setLayout(panelSelectorLayout);
        panelSelectorLayout.setHorizontalGroup(
            panelSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSelectorLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(botonInfanil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154)
                .addComponent(botonRomantica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonTerror, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );
        panelSelectorLayout.setVerticalGroup(
            panelSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSelectorLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(panelSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonInfanil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonRomantica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonTerror, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panelReproductor.setBackground(new java.awt.Color(255, 255, 204));

        panelAcciones.setBackground(new java.awt.Color(204, 204, 255));

        botonReiniciar.setText("Reiniciar");
        botonReiniciar.setMaximumSize(new java.awt.Dimension(100, 23));
        botonReiniciar.setMinimumSize(new java.awt.Dimension(100, 23));
        botonReiniciar.setPreferredSize(new java.awt.Dimension(100, 23));
        botonReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReiniciarActionPerformed(evt);
            }
        });

        botonSalir.setText("Salir");
        botonSalir.setPreferredSize(new java.awt.Dimension(100, 23));
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAccionesLayout = new javax.swing.GroupLayout(panelAcciones);
        panelAcciones.setLayout(panelAccionesLayout);
        panelAccionesLayout.setHorizontalGroup(
            panelAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAccionesLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(botonReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(184, 184, 184)
                .addComponent(contador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );
        panelAccionesLayout.setVerticalGroup(
            panelAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAccionesLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(panelAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelAcciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(panelReproductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panelSelector, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelReproductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelAcciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRomanticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRomanticaActionPerformed
        List<Imagen> lista = new ArrayList<>();
        lista.add(new Imagen(new ImageIcon(getClass().getResource("/ui/resources/romantica1.png")), 3));
        lista.add(new Imagen(new ImageIcon(getClass().getResource("/ui/resources/romantica2.png")), 3));
        lista.add(new Imagen(new ImageIcon(getClass().getResource("/ui/resources/romantica3.png")), 3));
        
        this.panelReproductor.cargarEscena(lista);
    }//GEN-LAST:event_botonRomanticaActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReiniciarActionPerformed
        this.panelReproductor.resetEscena();
    }//GEN-LAST:event_botonReiniciarActionPerformed

    private void botonTerrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTerrorActionPerformed
        List<Imagen> lista = new ArrayList<>();
        lista.add(new Imagen(new ImageIcon(getClass().getResource("/ui/resources/terror1.png")), 4));
        lista.add(new Imagen(new ImageIcon(getClass().getResource("/ui/resources/terror2.png")), 3));
        lista.add(new Imagen(new ImageIcon(getClass().getResource("/ui/resources/terror3.png")), 4));
        
        this.panelReproductor.cargarEscena(lista);
    }//GEN-LAST:event_botonTerrorActionPerformed

    private void botonInfanilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInfanilActionPerformed
        List<Imagen> lista = new ArrayList<>();
        lista.add(new Imagen(new ImageIcon(getClass().getResource("/ui/resources/infantil1.png")), 5));
        lista.add(new Imagen(new ImageIcon(getClass().getResource("/ui/resources/infantil2.png")), 4));
        lista.add(new Imagen(new ImageIcon(getClass().getResource("/ui/resources/infantil3.png")), 4));
        
        this.panelReproductor.cargarEscena(lista);
    }//GEN-LAST:event_botonInfanilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonInfanil;
    private javax.swing.JButton botonReiniciar;
    private javax.swing.JButton botonRomantica;
    private javax.swing.JButton botonSalir;
    private javax.swing.JButton botonTerror;
    private components.contador.ContadorBean contador;
    private javax.swing.JPanel panelAcciones;
    private javax.swing.JPanel panelPrincipal;
    private components.reproductor.ReproductorBean panelReproductor;
    private javax.swing.JPanel panelSelector;
    // End of variables declaration//GEN-END:variables
}
